name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@v1
      with:
        node-version: "25.8.1"
        cache: true

    - shell: bash
      run: vp install
