packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild

catalog:
  typescript: ^5.9.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.13

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
