packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@typescript/native-preview": 7.0.0-dev.20260321.1
  "@types/node": ^25.5.0
  arktype: ^2.1.20
  publint: ^0.3.18
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@latest

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - prisma

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
