"use client";
import { Check, Clipboard } from "@rectangular-labs/ui/components/icons";
import { Button } from "@rectangular-labs/ui/core/button";
import { useCopy } from "@rectangular-labs/ui/hooks/use-copy";
import { cn } from "@rectangular-labs/ui/utils";
import {
  type ComponentProps,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  useRef,
} from "react";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre {...props} className={cn("w-max min-w-full *:flex *:flex-col", props.className)}>
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => <div {...props} className={cn("empty:hidden", props.className)} />,
  ...props
}: CodeBlockProps) {
  const areaRef = useRef<HTMLDivElement>(null);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        "my-4 rounded-none bg-card",
        "group-data-slot/tab-content:my-0 group-data-slot/tab-content:-mx-px group-data-slot/tab-content:-mb-px  group-data-slot/tab-content:bg-secondary",
        // if we ever add radius, uncomment the below to have the bottom be rounded
        // "group-data-slot/tab-content:rounded-none tab-content:last:rounded-b-xl",
        // if we ever add padding the bottom can help compensate
        // "group-data-slot/tab-content:-m-4 group-data-slot/tab-content:border-none",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
        "shiki not-prose relative overflow-hidden border text-sm shadow-sm",
        props.className,
      )}
    >
      {title ? (
        <div className="flex h-9.5 items-center gap-2 border-b px-2 text-muted-foreground">
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            className: "-me-2",
            children: allowCopy && <CopyButton containerRef={areaRef} />,
          })}
        </div>
      ) : (
        Actions({
          className: "absolute top-2 right-2 z-2 backdrop-blur-lg rounded-lg text-muted-foreground",
          children: allowCopy && <CopyButton containerRef={areaRef} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        role="region"
        tabIndex={0}
        className={cn(
          "fd-scroll-container max-h-150 overflow-auto py-3.5 text-[0.8125rem] focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none focus-visible:ring-inset",
          viewportProps.className,
        )}
        style={
          {
            // space for toolbar
            "--padding-right": !title ? "calc(var(--spacing) * 8)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        {children}
      </div>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: ComponentProps<"button"> & {
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopy(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <Button
      type="button"
      data-checked={checked || undefined}
      className={cn("hover:text-accent-foreground data-checked:text-accent-foreground", className)}
      size="icon-xs"
      variant="ghost"
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      {checked ? <Check /> : <Clipboard />}
    </Button>
  );
}
