name: Preview Package
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


jobs:
  build:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish './packages/*' --comment=update --packageManager=pnpm